### ISSUE TITLE
Maven jakość -> wtyczki

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#10]
- [x] SpotBugs
- [x] CheckStyle
- [x] Jacoco

**Comment by atrzewik** [comment]
Jacoco info:
https://www.eclemma.org/jacoco/trunk/doc/ant.html
https://dzone.com/articles/reporting-code-coverage-using-maven-and-jacoco-plu

**Comment by atrzewik** [comment]
Wszyscy proszę o instalacje wtyczki: https://plugins.jetbrains.com/plugin/8527-google-java-format
