### ISSUE TITLE
Prototyp modelu ksiązki i jej relacji

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#100]
- [x] prototyp książki i księgarni
- [x] tabele w H2
- [x] prototyp HrefAndImage
- [x] prototyp BookstoreBook
- [x] parsowanie DTBook na encje

**Comment by sehta7** [comment]
Zablokowane do czasu scalenia devalopa z wtorku do mastera

**Comment by atrzewik** [comment]
Przydatne linki:
https://stackoverflow.com/questions/27215607/annotationexception-a-foreign-key-refering-has-the-wrong-number-of-column-shou
https://www.concretepage.com/hibernate/example-embeddedid-hibernate

**Comment by atrzewik** [comment]
Link do migawki: https://github.com/kamroj/robot/commit/0c88a6e7114a9f57dbd225c8418ecd963c52179d
