### ISSUE TITLE
Serwis do mapowania encji książki na dtosy

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#101]
- [x] stwórz metodę która zmienia liste książek z bazy danych na DTosy
- [x] stowrzenie testów dla klasy BookParser

**Comment by Ozonek95** [comment]
Wprowadzamy w trzecim sprincie.

**Comment by atrzewik** [comment]
Brak czasu - sprint 3

**Comment by atrzewik** [comment]
Linki do migawek:
https://github.com/kamroj/robot/commit/e12834dab812b83175725d1396e75bd3e06e14a0
https://github.com/kamroj/robot/commit/6cef0aa3f8ab5de68923cd087f19b160b064c0fb
