### ISSUE TITLE
CD -> dostarczanie na serwer i odpalenie/podmiana jarki

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#12]
- [x] Sprawdzić czym dokładnie jest continuous delivery i continuous deployment
- [x] ustawić "pipeline'y" do obu na Jenkinsie -> wdrażanie z gałęzi "master"
- [x] Sprawdzić jak zrobić deploy za pomocą komendy w CLI Heroku
- [x] Przetestować działanie za pomocą stworzenia nowego endpointu testowego i merge do mastera 
- [x] Stworzenie repozytorium herokowego

**Comment by TwojaTata** [comment]
Materiały:
https://dzone.com/articles/building-a-continuous-delivery-pipeline-using-jenk

**Comment by WRup** [comment]
Schemat postępowania wyglądał następująco:
Należało podłąćzyć Jenkinsa z repozytorium Herokowym. W moomencie kiedy łąćzymy Heroku z repozytorium gitowym to heroku tworzy sobie własne repozytorium, na którym trzyma wersję z danej gałęzi i ją wystawia na serwerze. Po stronie Jenkinsa należało dodać to herokowe repozytorium w konfiguracji, a następnie ustawić, że po udanej budowie projekt jest wypychany właśnie na to herokowe repozytrium. Heroku jak zobaczy że ktoś coś wypchnął to automatycznie wystawia ją na serwer. Aby Jenkins mógł wypychać na heroku to musi mieć do niego dostęp. Dostęp ten uzyskał poprzez API Heroku token, który można wyciągnąć komendą : heroku auth:token
