### ISSUE TITLE
Wydzielenie poziomu abstrakcji ze Scrapperów

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#132]
Mamy 3 klasy zdzierające informacje ze stron, które są do siebie łudząco podobne, trzeba wydzielić ich funkcjonalność i stworzyć klasę abstrakcyjną, po której dziedziczą
- [x] Wydzielenie wspólnej funkcjonalności
- [x] Stworzenie klasy abstrakcyjnej implementującej wspólną funkcjonalność
- [x] Zaimplementowanie konkretnych klas z implementacją metod abstrakcyjnych
- [x] Stworzenie @Configuration konfiguracji springowej z ziarnami dla kontekstu aplikacji
- [x] Przerobienie testów integracyjnych, żeby działały z nowymi klasami.

**Comment by Ozonek95** [comment]
Stworzyłem klasę AbstractScrapper, który automatycznie generuje nowe adresy URL oraz trzyma informacje na temat wyciąganego dokumentu przez JSoup. Posiada metodę abstrakcyjną do wyciągania danych z konkretnej księgarni (ponieważ kod HTML każdej z nich się różni). Po implementacji konkretnych klas stworzyłem klasę ScrapperConfiguration, która tworzy wszystkie potrzebne ziarna. Na koniec zmieniłem testy integracyjne każdej księgarni, żeby były zgodne z nową implementacją.

**Comment by Ozonek95** [comment]
Link do PR : https://github.com/kamroj/robot/pull/159
 Miłej zabawy ;D
