### ISSUE TITLE
Refaktor kodu EntityMenagerFactory

### ISSUE THREAD

**Issue by Ozonek95** [kamroj/robot#135]
Zrefaktorować kod w EntityMenager - był szybki fix przed zamrożeniem kodu.
- [x] dodanie metody Close() do api ConnectorProvider - zamykanie fabryki menadżerów encji
- [x] dodać dokumentacje do nowego API
- [x] zrefaktoryzować metodę getEntityManagerFactory
- [x] dodać dokumentacje do metody getEntityManagerFacotry
- [x] zrefaktoryzować wszystkie użycia entityManager.close() na connectionProvider.close();
- [x] sprawdzić poprawność ilości połączeń i czy połączenia po skończeniu pracy poprawnie się zamykają

**Comment by kamroj** [comment]
Primo, jeżeli zamkniemy EntityManagerFactory to wszystkie EntityManager z tej fabryczki ulegają automatycznej zmiany stan na closed.
Po drugie, zastanawiam się czy nie lepiej jak będziemy mieli po prostu jedną fabrykę per jeden ConnectorProvider, przez co zamknięcie danego dostawcy będzie równoważyło się z zamknięciem połączenia do bazy.

**Comment by kamroj** [comment]
!WAŻNE INFO!
Używajcie API connectorProvider.close() w przypadku kiedy chcecie zamknąć wszystkie menadżery encji ( daną fabrykę, która te menadżery stworzyła ). Zamyka to dane połączenie z bazą danych.
W przypadku kiedy w waszej klasie kilkukrotnie będziecie chcieli działać na danej encji a dopiero potem będzie chcieli zamknąć połączenie z bazą danych, to tworzycie connectionProvider.getEntityManager() -> otwieracie sesje -> persystujecie zmiany i tak w kilku metodach. Po zakończeniu pracy z bazą danych (tak jak wyżej) wywołujecie metodę connectionProvider.close();
