### ISSUE TITLE
Model książki

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#14]
- [x] Autor, Tytuł, Gatunek, Szczegóły promocji, cena, księgarnia/witryna
- [x] zaadnotować/skonfigurować w XML'u

**Comment by kamroj** [comment]
W JSON nie ma póki co informacji o promocji. Dlatego model nie zawiera takiej zmiennej.

**Comment by TwojaTata** [comment]
https://github.com/kamroj/robot/pull/39#pullrequestreview-260507705
