### ISSUE TITLE
Sortowanie wyników wyszukiwania na froncie

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#147]
Sortowanie wyników po wskazanym atrybucie. Na początek cena i alfabetycznie po autorze i tytule 
- [x] Stworzenie pipe  sortBy
- [x] Zaimporotwanie biblioteki lodash
- [x] Implementacja sortowania
- [x] Możliwość sortowania po naciśnięciu nazwy w tabeli
- [x] Stworznie spanu przy nazwie tabeli i stylowanie ( odwrócenie o 180 stopni ) w zalezności od rodzaju sortowania
- [x] Dodanie kolumny z mozliwością wyboru poszeczególnych bibliotek za pomocą przecisku radio
- [x] Dodanie  przycisku z ograniczeniami cenowymi

**Comment by Kapaika** [comment]
problem z sortowaniem cen ; różne waluty, porównywanie cen które są stringami

**Comment by Kapaika** [comment]
stworzony pipe do sortowania po cenie, ale póki co nie ma mozliwości dokładnego filtrowania przez to, że cena podawana jest jako String
