### ISSUE TITLE
Paginacja na backendzie

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#148]
Trzeba przygotować gotowe zestawy wyników o konkretnych ilościach do wyświetlenia. Kamil chciał to zadanie, więc konsultować się z nim
- [x] zrobienie prototypu paginacji gorliwej
- [x] zrobienie prototypu paginacji leniwej
- [x] dodanie możliości filtrowania w paginacji leniwej
- [x] rozbicie klasy paginacji aby nie była odpowiedzialna za sięganie po rekordy do bazy danych
- [x] dodanie enuma jako typu filtra
- [x] wystawienie endpointów paginacji leniwej
- [x] przerobienie endpointu dotyczącego wyboru filtru z metody http  GET na REQUESTMAPPING po enumie filtru
- [x] dodanie podstawowych filtrów przy paginacji leniwej
- [x] dodanie możliwości wyboru rozmiaru paginacji - 10/20/50/100
- [x] stworzenie API do paginacji
- [x] zaimplementowanie API paginacji w klasie paginacji gorliwej
- [x] dodanie możliości filtrowania w paginacji gorliwej
- [x] rozbicie odpowiedzialności klasy paginacji gorliwej -> osobna klasa na filtracje
- [x] ugenericznić API paginacji
- [x] stworzenie kontrolera paginacji
- [x] przeniesienie kodu z BookController do PaginationController
- [x] oznaczenie klasy BookController jako @Depracated
- [x] rozwiązać problem z zamykaniem połączenia do bazy a paginacją leniwą - by nie trwało wieki wieków
- [x] dodanie dokumentacji do wszystkich klas
- [x] stworzenie metody fabrykującej paginacje

**Comment by kamroj** [comment]
Dodałem prototypy dwóch różnych paginacji:
1. Paginacje statyczną - ładuje wszystkie rekordy do mapy i na tym obiekcie bazujemy ( przekazujemy odpowiednią ilość rekordów, filtrujemy odpowiednio liste itp). - boje się trochę o pamięć, że się wykrzaczy.
2. Paginacje dynamiczną - w czasie rzeczywistym pobieramy z bazy danych odpowiednią ilość rekordów. Póki co w prototypie są trzy endpointy: a) startujący, b) następna strona, c) poprzednia strona.

Jutro będę to doszlifowywał, dodawał możliwości różnych filtrów itp.

**Comment by kamroj** [comment]
PROBLEM:
w przypadku paginacji dynamicznej musimy utrzymywać cały czas połączenie do bazy danych. Każdorazowe odnawianie połączenia z bazą danych trwa wieki.

**Comment by kamroj** [comment]
ENDPOINTY PAGINACJI LENIWEJ:
1. Początkowe wyświetlenie rekordów `/books/pagination`
2. Kolejna strona `/books/pagination/next`
3. Poprzednia strona `/books/pagination/previous`
4. Zmiana filtra (tymczasowo na metodzie GET) `/books/pagination/filter` -> filtruje ceny promocyjne rosnąco
5. Filter domyślny (tymczosowo na metodzie GET) `/books/pagination/filterd` -> rosnąco po ID

Wybór filtru będzie zmieniony z metody GET na POST i w ten czas będziemy przesyłali odpowiedniego JSONa który zmieni nam filter.
