### ISSUE TITLE
Serwis do uderzania pod API księgarni i pobierania JSON'a

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#15]
Utworzenie serwisu łączącego się z wybraną ksiągraną / biblioteką za pomocą REST API  w celu uzyskania danych na temat książek się tam znajdujących.

- [x] Rozpoznanie tematu
- [x] Wysłąnie zapytania pod konkretne API
- [x] Delegowanie odpowiedzi do kolejnego serwisu
- [x] Refraktor serwisu
- [ ] Testy jednostkowe
- [x] Utworzenie dokumentacji

**Comment by marcinogo** [comment]
Na początek planujemy łączyć się z: https://api.itbook.store/

**Comment by TwojaTata** [comment]
implementacja testów jednostkowych chwilowo wstrzymana
