### ISSUE TITLE
Skrypt do haseł i loginów

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#156]
Prosty skrypt do udostępnienia lokalnie tworzący odpowiednie zmienne globalne z przypisanymi hasłami i loginami. Oprócz tego mapa -> pod jaką zmienną co jest i jak się do niej dostać
- [x] Zebrać dane potrzebne do logowania
- [x] Napisać skrypt
- [x] Testowanie i rozdystrybuowanie skryptu

**Comment by WRup** [comment]
Informacje odnośnie każdej zmiennej środowiskowej znajdują się na wiki. Poniżej link do wiki:
https://github.com/kamroj/robot/wiki/For-Developers-Credentials
