### ISSUE TITLE
Sonar lokalnie

### ISSUE THREAD

**Issue by sehta7** [kamroj/robot#174]
Trzeba ustawić konfiguracje dla sonara, żeby można było go odpalać lokalnie w przeglądarce spod naszego adresu 80.211.241.126:9000, dzięki temu jenkins będzie mógł się połączyć.
Część zadania #9

**Comment by marcinogo** [comment]
Zadanie porzucone ponieważ udało się uruchomić SonarQube zdalnie oraz połączyć go z Jenkinsem.
