### ISSUE TITLE
Wybór księgarni z odpowiednim API

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#18]

**Comment by WRup** [comment]
Na chwilę obecną znalazłem takie API:
https://api.itbook.store/ - proste, bez rejestracji, dostarczające podstawowe informacje, prosty JSON
https://developer.penguinrandomhouse.com/io-docs - potrzebna rejestracja, w tej chwili czekam na aktywację konta. Logowanie tymi samymi kredkami jak do maila. JSON trochę bardziej złożony, ale dostarczjący więcej informacji.
