### ISSUE TITLE
Szkielet modułów

### ISSUE THREAD

**Issue by sehta7** [kamroj/robot#26]

**Comment by kamroj** [comment]
- [ ] stworzenie modułu "database"
- [ ] stworzenie modułu "temporary" ( przykładowy / tymczasowy )
- [ ] przetestowanie komunikacji między modułami
- [ ] przetestwoanie zbudowania pliku JAR oraz odpaleniu go z poziomu konsoli

**Comment by kamroj** [comment]
Raczej do kosza :(
