### ISSUE TITLE
Przygotowanie projektu

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#28]
- [x] Repozytorium Gitowe
- [x] Projekt z mantry
- [x] README.adoc
- [x] .gitingore
- [x] .mailmap
- [x] gitattributes
- [x] pom.xml

**Comment by kamroj** [comment]
- [] stworzenie projektu za pomocą mantry
- [] przygotowanie wstępnie POM.xml ( docelowo aga zajmuje się jakością wtyczek )

**Comment by TwojaTata** [comment]
https://github.com/kamroj/robot/pull/39#pullrequestreview-260507705
