### ISSUE TITLE
Postawić Jenkinsa na serwerze CI

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#3]
- [x] Zainstalować mavena
- [x] Zainstalować Javę
- [x] Wytczki do Jenkinsa - github, maven itd
- [x] Podpiąć repozytorium
- [x] Próbna budowa

**Comment by Ozonek95** [comment]
Problem z Heroku. Przenosimy serwer CI na Arubę, następnie tam będziemy stawiać Jenkinsa.

**Comment by Ozonek95** [comment]
80.211.241.126:8080 tu stoi Jenkins. Działa. Wreszcie.

**Comment by TwojaTata** [comment]
Jenkins działa, ale nie wszystko jest skonfigurowane. Na razie zatrzymujemy zadanie ze względów na inne priorytety
