### ISSUE TITLE
Zmienić dane autentykacyjne po postawieniu serwera.

### ISSUE THREAD

**Issue by kamroj** [kamroj/robot#30]
- [ ] zmienić nazwe użytkownika oraz hasło dla bazy danych PostgreSQL
- [ ] zmienić nazwe użytkownika oraz hasło dla bazy danych H2

**Comment by kamroj** [comment]
- [] zmienić nazwe użytkownika oraz hasło dla bazy danych PostgreSQL
- [] zmienić nazwe użytkownika oraz hasło dla bazy danych H2

**Comment by WRup** [comment]
Nazwa użytkownika oraz hasło do bazy danych generowane są automatycznie przez algorytmy Heroku. Nie ma możliwości ustawienia ich manualnie, jest ewentualna możliwość ich zmiany, co opisałem w zadaniu #5 - Postawić bazę danych na serwerze

**Comment by WRup** [comment]
O co chodzi ze zmianą nazwą użytkownika i hasła do bazy danych H2? Z tego co się orientuje korzystamy tylko z Postgre? @KRojek
