### ISSUE TITLE
Zmiana testów integracyjnych na jednostkowe

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#49]
Testy dla serwisów muszą zostać zamokowane:
- [x] testy dla ITBookMapper
- [x] testy dla BookDataDownloader

Po za tym:
- [x] testy dla BookstoreConnector przenieść do testów integracyjnych
- [x] dodanie maven failsafe plugin do poma do omijania testów integracyjnych
- [x] dodanie builder helper plugin to poma żeby mieć możliwość posiadanie osobnej paczki na testy integracyjne
- [x] dodanie testów dla BookService class

**Comment by atrzewik** [comment]
Przydatne linki:
http://maven.apache.org/surefire/maven-failsafe-plugin/examples/skipping-tests.html
https://stackoverflow.com/questions/17117589/how-can-i-skip-tests-in-maven-install-goal-while-running-them-in-maven-test-goa
