### ISSUE TITLE
Postawić bazę danych na serwerze

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#5]
PostgreSQL, na heroku są do tego tutoriale

- [x] Konfiguracja bazy danych
- [x] Dokumentacja Postegre na heroku
- [x] Zrozumienie "Dataclips"
- [x] Postawienie bazy danych na serwerze z domyślna konfiguracją

**Comment by WRup** [comment]
Obecnie baza danych jest postawiona z domyślną konfiguracją na serwerze heroku oraz jest przypisana do aplikacji bookrobotja7.

**Comment by WRup** [comment]
W przypadku jakiegoś spadku wydajności bazy danych można ją zdiagnozować następującą metodą:
heroku pg:diagnose --app bookrobotja7

Jeżeli byłyby problemy z połączeniami do bazy danych możemy skorzystać z PgBouncer.

Niektóre kwerendy mogą się wykonywać dłużej i blokować działanie bazy danych. Zwykle takie blokady są wychwytywane i szybko usuwane, ale zdarzają się patologiczne sytuacje i wtedy mozemy ręcznie zabić taką kwerendę metodą:
heroku pg:kill <tutaj_id_kwerendy>
Aby zobaczyć kwerendy obecnie wykonywane możemy użyć komendy:
heroku pg:ps -a bookroobotja7


Możemy podłączyć się pod naszą serwerową bazę zdanie z naszego komputera.  Żeby działało musimy mieć oczywiście zainstalowane Postgre na naszym systemie:
heroku pg:psql -a boookrobotja7

Następnie możemy pobrać sobie aktualne dane na naszą bazę lokalna (np. dla testów).
heroku pg:pull postgresql-horizontal-53980 mylocaldb --app bookrobotja7

Powyższa komenda tworzy nową lokalną bazędanych o nazwie "mylocaldb" i ściąg wszystkie dane z bazy serweowej postgresql-horizontal-53980. 

Możemy sobie ustawić kredki dla naszej lokalnej bazy następującą komendą:
PGUSER=postgres PGPASSWORD=password heroku pg:pull postgresql-horizontal-53980 mylocaldb --app bookrobotja7

**Comment by marcinogo** [comment]
Zrecenzowane
