### ISSUE TITLE
Haki gitowe

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#6]
Utworzenie haków gitowych. W tej iteracji najprostrza możliwa forma czyli brak możliwości utworzenia migawki gdy projek się nie buduje. Dodatkowo niezbędny jest skrypt uaktywniajacy hak oraz umieszczający go w odpowiedniej lokalizacji.

- [x] Zrobić pre-commit hak
- [x] Napisać skrypt kopiujący hak
- [x] Zaktualizowanie .gitignore o wpis dla plików tymczasowych odplanych skryptów
- [x] Dodanie informacji o skryptach w README
- [x] Naprawienie działania haka

**Comment by marcinogo** [comment]
Wykonałem podstawowy skrypt pre-commit do git hooks odpalający mvn clean package. Reszta kodu haka pochodzi z przykładu tam będącego. Wykonałem również skrypt kopiujący haka w odpowiednie miejsce.
Dodatkowo zakualizowałem README i gitignore.

**Comment by marcinogo** [comment]
Hak wyświetla poprawne wiadomości ale dposzucza utworzenie migawki mimu nieprzejścia mvn clean package.
