### ISSUE TITLE
Wprowadzenie CriteriaBuilder.

### ISSUE THREAD

**Issue by krzysztofkramarz** [kamroj/robot#66]
Refaktor klasy BookRepository. W tej klasie używamy persisntenrManager.createQuery. 
Trzeba zamiast tego użyć  CriteriaBuildera .
- [x] refactor klasy BookRepository

**Comment by TwojaTata** [comment]
Gdzie mogę to zrecenzować???

**Comment by marcinogo** [comment]
Merge konflikty, nie będzie recenzowane do czasu ich rozwiązania.
