### ISSUE TITLE
serwis zapisujący

### ISSUE THREAD

**Issue by sehta7** [kamroj/robot#68]
dodanie nowych księgarni do zapisu w bazie - trzeba zaczekać na zdrapanie empiku i pwn, lub nowe api

**Comment by WRup** [comment]
Zadanie chwilowo blokowane, ponieważ trzeba zaczekać na zdrapanie empiku i pwn, lub nowe api.
#73 zdrapywanie - pwn
#95 zdrapywanie - Świat książki
