### ISSUE TITLE
ujednolicenie modelu

### ISSUE THREAD

**Issue by sehta7** [kamroj/robot#70]
Edycja encji ksiązki i dodanie potrzebnych encji do stworzenia pełnej bazy, włącznie z promocjami
- [x] dyskusja
- [x] książka
- [x] inne

**Comment by sehta7** [comment]
Wstępnie gotowe encje: Książka, Księgarnia, KsiążkaKsięgarnia

**Comment by atrzewik** [comment]
Brak czasu - sprint 3

**Comment by atrzewik** [comment]
Link do migawki: https://github.com/kamroj/robot/commit/331db57edcfc46036cdd1ff0225bfdadaa1e0b88
