### ISSUE TITLE
zdrapywanie - empik

### ISSUE THREAD

**Issue by sehta7** [kamroj/robot#72]
- [x] Znalezienie url z promocjami książek
- [x] Skontrolowanie elementu i znalezienie klasy reprezentujące poszczególną ksiązkę
- [x] Znalezienie klasy reprezentującej poszczególne pola w klasie Book tj. tytuł, podtytuł, autor itp.
- [x] Rozpoznanie biblioteki Jsoup
- [x] Zaciągnięcie zalezności do projektu
- [x] Stworzenie metody która zdrapuje przecenione ksiązki
- [x] Staworznie metody która zdrapuje poszczególne pola
- [x] Stworzenie instancji Book na podstawie zdrapanych stringów
- [x] Zaimplementować zdrapywanie kilku stron jednocześnie (wielowątkowość)
- [x] zaimplementowanie równoległego mapowania na modele (wielowontkowość)
- [x] Zamienić wartości price i promotion miejscami.

**Comment by Kapaika** [comment]
https://jsoup.org/ - strona biblioteki wykorzystywanej do zdrapywania strony

**Comment by Kapaika** [comment]
https://www.empik.com/promocje?searchCategory=31&hideUnavailable=true&qtype=facetForm - url z Książkami w promocji.

**Comment by Ozonek95** [comment]
Zrównoleglenie poprzez użycie ExecutorService. Wątki egzekutora uderzają pod dany adres i mapują otrzymaną odpowiedź na encję. W aktualnej implementacji używamy 30 wątków do wykonywania operacji. Używamy Phasera, żeby zwrócić listę książek dopiero jak wszystkie wątki skończą zadanie. Pierwsze testy sugerują wzrost wydajności o conajmniej 500%

**Comment by Kapaika** [comment]
javax.net.ssl.SSLException: No PSK available - wyjątek wyrzucany w momencie w któym chcemy zdrapać za dużą liczbę stron na raz

**Comment by Ozonek95** [comment]
Stworzyliśmy implementację interfejsu IPromotionScrapping, która zdziera danie z Empika, tworzy z nich listę encji Book gotowych do zapisu do bazy.

**Comment by Ozonek95** [comment]
Stworzyliśmy test integracyjny do funkcjonalności.
