### ISSUE TITLE
konta użytkowników na jenkinsie

### ISSUE THREAD

**Issue by sehta7** [kamroj/robot#74]
Stworzyć konta użytkowników na Jenkinsie

**Comment by sehta7** [comment]
Oczekiwanie na certyfikat

**Comment by kamroj** [comment]
LetsEncrypy było najlepszą decyzją, więc:
- opcja pierwsza - próbujemy podmienić certyfikaty,
- opcja druga - stawiamy jenkinsa na nowo z poprawnymi certyfikatami

**Comment by Ozonek95** [comment]
Konta użytkowników nie będą nam potrzebne do wysyłania maili. Jenkins sam wyciąga adres email na podstawie dokonanych migawek.
