### ISSUE TITLE
Aktualizacja git haków

### ISSUE THREAD

**Issue by sehta7** [kamroj/robot#75]
Dodanie nowej wiadomości podczas wykonywania skryptu nadającego uprawnienia i kopiującego haki gitowe. Głownym celem jest ujednolicenie języka (przejście na komunikaty tylko w języku angielskim).
- [x] Zmiana tekstu wiadomości z języka polskiego na angielski
- [x] Dodanie wiadomości informującej o zakończeniu wykonywania skryptu kopiującego

**Comment by marcinogo** [comment]
Pull request na to zadanie: https://github.com/kamroj/robot/pull/83
