### ISSUE TITLE
maile na Jenkinsie

### ISSUE THREAD

**Issue by sehta7** [kamroj/robot#76]
Dodanie maili użytkowników, do których zostanie wysłana wiadomość, jeśli build nie przejdzie
- [x] Rozpoznanie
- [x] Konfiguracja skrzynki emailowej
- [x] Zmiana ustawień na Gmailu
- [x] Wysłanie emaili testowych
- [x] Wysłanie emaila w przypadku udanej budowy do wyznaczonych odbiorców

**Comment by sehta7** [comment]
Oczekiwanie na certyfikat

**Comment by marcinogo** [comment]
Możliwe, że problem z wysyłąniem email wynikał z niepoprawnej konfiguracji po stronie Jenkinsa oraz restrykcyjności Gmaila. Rozwiązanie: https://www.decodingdevops.com/configure-jenkins-email-notification-and-solved-not-working/.
Emaile wysyłane są za pośrednictwem skrzynki projektowej: Zmień bookrobot.ja7@gmail.com
