### ISSUE TITLE
certyfikacja

### ISSUE THREAD

**Issue by sehta7** [kamroj/robot#78]
Certyfikacja serweru, żeby google nie miał problemu z niebezpiecznymi źródłami
- [x] Uzyskanie certyfikatu SSL
- [x] Uzyskanie domeny
- [x] Skojażenie domeny z IP i portem Jenkinsa
- [x] utworzyć CSR

**Comment by marcinogo** [comment]
Brak certyfikatu SSL powoduje generowanie ostrzeżeń oraz konieczność używania HTTP zamiast HTTPS.

Rozwiązaniem jest zainstalowanie certyfikatu na serwerze. Wybór padł na rozwiązanie open source.
Istalacja certyfikatu z https://letsencrypt.org/ / https://certbot.eff.org/ wymaga posiadania domeny a nie tylko IP.
Wykupieno domenę na home.pl - jenkins-nasz-pan.pl (logowanie w panelu użytkownika przez https://cp.home.pl/) oraz 
ustawieno reverse DNS na Aruba Cloud.
Poniesiono koszta w wysokości 1,23 PLN oraz możliwe, że Aruba będzie naliczać opłaty - należy to monitorować.

Niestety nie udało się skojarzyć IP i portu Jenkinsa (80.211.241.126:8080) z wyżejwymienoną domeną.
Problem pozostaje nie rozwiązany po 4 godzinach pracy.

**Comment by kamroj** [comment]
Kredki do konta na home.pl :
użytkownik: bookrobot.ja7@gmail.com
hasło: Technicznep11:15

**Comment by sehta7** [comment]
stworzyłam certyfikat przez stronę https://community.arubanetworks.com/t5/Controller-Based-WLANs/How-do-I-replace-the-default-Aruba-SSL-certificate/ta-p/178060, ale nie jestem w stanie wykonać ostatniego punktu, czyli podmienić domyślny certyfikat na nasz, ani przez terminal ani przez aruba controller

**Comment by sehta7** [comment]
rozwiązanie Krzysia, które daje nam samopodpisany certyfikat: https://hostadvice.com/how-to/how-to-install-a-self-signed-ssl-certificate-for-apache-on-ubuntu-18-04-server/ --> działało, ale występowało ostrzeżenie, ale ogólnie w tej chwili nie działa

**Comment by krzysztofkramarz** [comment]
zadanie rozwiązane po wykonaniu komend z tej strony
https://certbot.eff.org/lets-encrypt/ubuntuxenial-apache.html
