### ISSUE TITLE
skrypt do zmiennych środowiskowych

### ISSUE THREAD

**Issue by sehta7** [kamroj/robot#80]
Napisanie skryptu, który sprawdza, czy ustawione zmienne są poprawne
- [x] Napisanie skryptu bashowego
- [x] Sprawdzenie możliwości wykonania skryptu przez heroku
- [x] Ustalenie częstotliwości wykonania skryptu
- [x] Czy hasła trzymane w skrypcie powinny być jawne?
- [x] Implementacja wykonywania skryptu w aplikacji jawowej

**Comment by WRup** [comment]
Hasła nie będą trzymane jawnie w skrypcie, będą pobierane z pliku konfiguracyjnego bazy danych

**Comment by WRup** [comment]
Aby heroku mógł wykonywać skrypt co jakiś czas niezbędne jest zainstalowanie odpowiednich wtyczek. Wtyczki te są darmowe, aczkolwiek żeby je zainstalować należy potwierdzić swoją osobowość dodająć kartę kredytową.
Porzuciliśmy ten pomysł i jest próba implementacji tego zadania w kodzie jawowym.

**Comment by WRup** [comment]
Czekam na kontroler, który będzie wyznacznikiem uruchomienia skryptu bashowego. - #71 intergracja robota

**Comment by WRup** [comment]
https://github.com/kamroj/robot/pull/134
