### ISSUE TITLE
refactoring

### ISSUE THREAD

**Issue by sehta7** [kamroj/robot#86]
Poprawki od klienta, ogólny refactoring kodu

**Comment by marcinogo** [comment]
@atrzewik prosiłbym o dodanie listy poprawek wymaganych przez klienta w komentarzu

**Comment by atrzewik** [comment]
niestety są przetrzymywane w urządzeniu @TwojaTata :D

**Comment by TwojaTata** [comment]
https://grabarzkuchar-laq9195.slack.com/messages/DHU310DSA/

Prosze bardzo

**Comment by Ozonek95** [comment]
https://github.com/kamroj/robot/pull/112
