### ISSUE TITLE
sprawdzenie api googla

### ISSUE THREAD

**Issue by sehta7** [kamroj/robot#87]
https://developers.google.com/books/docs/v1/reference/bookshelves
Przejrzenie google books api

- [ ] uzyskanie dostępów
- [ ] sprawdzenie api
- [ ] przyjęcie/odrzucenie

**Comment by atrzewik** [comment]
W api googla brak informacji o promocji, czy chcemy dalej je rozważać, czy szukamy czegoś innego @kacperstaszek1995 ?

**Comment by sehta7** [comment]
W takim razie porzucamy i zajmujemy się tą Wiktorową

**Comment by marcinogo** [comment]
Moim zdaniem należy porzuci ć w takim razie.

**Comment by WRup** [comment]
Jeżeli nie ma promocji to też jestem za porzuceniem, bo taką bez promocji mamy w tej chwili, więc na dłuższą metę się nie przyda.

**Comment by Ozonek95** [comment]
Abort mission.
