### ISSUE TITLE
Postawienie i konfiguracja Sonar Qube na serwerze

### ISSUE THREAD

**Issue by TwojaTata** [kamroj/robot#9]
Zwiększenie jakości kodu poprzez integrację SonarQube ( i jego bramek jakościowych) w proces CI / CD wykonywany przez Jenkinsa.
- [x] na dobry początek powstawie sonarka u siebie na localhost:9000
- [x] przenieść sonarka na serwerek jenkinsowy
- [x] stworzenie tokena
- [x] dostać się na localhost
- [x] certyfikacja serwera
- [x] ustawienie proxy dla Jenkinsa i Sonara (przekierowanie ruchu na https oraz sonara na odpowieni kontekst)
- [x] zmina bazy danych SonarQube z heroku na arubę (Postgresql)
- [x] stworzenie projektu uruchamiajacego SonarQube na Jenkinsie
- [x] ustawienie Analysis Parameters w pliku sonar-jenkins.properties

**Comment by sehta7** [comment]
Sonar działa już na naszym serwerku, ale nie ma dostępu do projektu i nie ma możliwości stworzenia tokenu (problem z dostaniem się na localhost przez terminal)

**Comment by sehta7** [comment]
Sprawa wygląda następująco:
Sonar jest postawiony na serwerze Aruba, odpala się i próbuje połączyć z bazą danych na Heroku. Tutaj jednak zostaje zablokowany ponieważ serwer Auba nie ma certyfikatu SLL i baza danych Postgre (która tak naprawdę jest hostowana przez AWS) nie pozwala na połączenie z serwerem niezabezpieczonym tj. bez certyfikatu.

**Comment by sehta7** [comment]
,m

**Comment by sehta7** [comment]
"Krótkie" wyjaśnienie co i jak z sonarem.
Po uzyskaniu certyfikacji pojawiły się problemy z bazą Postgresql - nie pozwalała na niebezpieczne połączenie, wyłączona była opcja ssl ("ssl off"). Nie było też potrzebnego pliku, który powinien stworzyć się przy inicjalizacji bazy - 'pg_hba.conf', który na naszym serwerze powinien być w folderze /var/lib/postgresql/9.5/main/data, ale takowy nawet nie istniał.
1. Najpierw więc trzeba zabrać się za stworzenie pliku --> https://stackoverflow.com/questions/44104241/postgresql-error-initdb-command-not-found, komenda 'locate initdb' pozwalała znaleźć miejsce, z którego powinna zostać zainicjalizowana baza, flaga -D określała ścieżkę, w której wszystko zostanie zapisane, całościowo na naszym serwerze komneda wyglądała bardzo intuicyjnie: '/usr/lib/postgresql/9.5/bin/initdb -D /var/lib/postgresql/9.5/main/data'
2. Folder z pliczkiem był gotowy, ale nadal występował związany z nim błąd: "FATAL: no pg_hba.conf entry for host". Żeby postgres wiedział, że nasz host jest ok i nie ma się, co bać, trzeba było ustawić w pliku posgresql.properties w folderze /data adres, na którym ma nasłuchiwać baza (https://dba.stackexchange.com/questions/83984/connect-to-postgresql-server-fatal-no-pg-hba-conf-entry-for-host), czyli nasz "listen_addresses = '80.211.241.126'", to samo trzeba było dodać w powstałym pliku 'pg_hba.conf', który okazał się być święty
3. Ale dla postgresa to wciąż mało i mało, bo przecież co z tego, że mamy samopodpisany certyfikat zdecydowanie świadczący o naszej wiarygodności. Postgres musi być pewny, że świadomi praw i obowiązków chcemy korzystać z ssll. Strona https://docs.sonarqube.org/display/SONARQUBE52/Running+SonarQube+Over+HTTPS pozwalała na jego odblokowanie. W drugim zaproponowanym podejściu należało ustawić port, wygenerowany klucz i hasło (dość dziwne rozwiązanie i raczej nie spełniało swojej roli, i pewnie dalej tego nie robi). Z racji nikłej zmiany w logach (/opt/sonarqube/logs - polecam pliczki "web.log" oraz "es.log") znowu zagłębiliśmy się w internety i po dłuuugich poszukiwaniach okazało się, że cały wielki problem z ssl można było rozwiązać dodając do ścieżki kierującej do bazy kilka istotnych słów "&ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory" (ze strony: https://stackoverflow.com/questions/17377118/heroku-database-connection-properties) i wszystko się odblokowało! Hip hip hura, bazka ruszyła, sonar zaczął tworzyć tabelki, ale..
4. ..ale nie dało się go odpalić lokalnie, tylko z serwera :( żeby takie cuda zadziałały, trzeba wejść na stronę https://admin.dc3.arubacloud.pl/Login.aspx z naszą kochaną arubą i się zalogować. Następnie w prawym górnym rogu kliknąć PL1 -> MANAGE -> GO TO CONSOLE, tam zalogować się  (co zabawne nie jako użytkownik Sonar, ale jako Other) na roota naszym hasełkiem (które nigdzie nie wypłynęło :p) i pod adresem 80.211.241.126:9000 można dostać się do sonara (narazie bez naszego projektu, który ma zostać połączony przez jenkinsa)
5. Przez połączenie na serwerze udało się stworzyć upragniony token. Kroki wyglądały następująco: zakładka Administration -> zakładka Security -> zakładka Users i po prawej stronie można było "manage token". Została ostatnia rzecz, czyli dodać go do konfiguracji sonara na jenkinsie. "Na easyiku"..
6.  Manage Jenkins -> Configure System i jedziemy według tutorialka: https://medium.com/@amitvermaa93/jenkins-sonarqube-integration-129f5c49c4ca. Niestety po drodze napotkaliśmy za mało problemów, więc a jakże uparty token też nie da się tak łatwo dodać. Trzeba było znowu kombinować i ominąć błąd związany z "security warning", który prawdopodobnie jest jakimś bugiem w kolejce do rozwiązania oraz pusty error, który jest raczej mało wymowny.
7. Pomocny miał się okazać plugin (tłum. wtyczka) Credentials (https://github.com/jenkinsci/gitlab-plugin/issues/617), ale samowystarczalny jenkins stwierdził. że takowego nie potrzebuje, więc w dostępnych wtyczkach go nie było. Zbawienna okazała się dokumentacja (https://github.com/jenkinsci/credentials-plugin/blob/master/docs/user.adoc - oczywiście nie czytałam całej, ale pooglądałam rysuneczki). Wybieramy zakładkę Credentials -> System -> Global Credentials i w lewym górnym rogu szukamy "add credentials". W ten sposób dodałam utworzony token, jako secret text o id 'sonar'. Radujmy się z niego wszyscy.
8. Reszta była już dziecinnie prosta (trzeba tylko pamiętać o zapisywaniu opcji w lewym dolnym rogu! ważna czynność, którą warto powtarzać bez przerwy). Według wcześniej wspomnianego tutoriala, trzeba było w Manage Jenkins -> Configure System, pod SonarQube servers dodać URL i nasz token. Potem tylko wskazać jenkinsowi plugin ze SonarQube Scanner, dodać plik określający opcje dla sonara (u nas dwie podstawowe: nazwa projektu i folder, z którego skanuje pliki). Znajduje się on w folderze /opt/sonarqube/conf pod nazwą "sonar-jenkins.properties". Także wszystko powoli zmierza do szczęsliwego zakończenia. Trzeba jeszcze tylko ustawić, żeby można było łączyć się z sonarem lokalnie, a w tej kwestii to już czaruje Marcin.
Ja zostawiam Was w tym martwym punkcie, bo "szczęśliwej drogi już czas" :D

**Comment by marcinogo** [comment]
Ustawiono certyfikację serwera: Isseue #78. Następnie niezbędne było ustawienie proxy w konfiguracji Apacha2 w pliku /etc/apache2/mods-enabled/proxy.conf (https://docs.sonarqube.org/display/SONARQUBE52/Running+SonarQube+behind+a+Proxy oraz https://www.digitalocean.com/community/questions/how-to-enable-ssl-for-both-jenkins-and-sonarqube-running-on-the-same-server). W pliku /opt/sonarqube/conf/sonar.properties ustawiono context=/sonar

W tym momencie pojawił się problem przy połączeniu pod adresem https://jenkins-nasz-pan.pl/sonar z kodem 503. "FATAL: no pg_hba.conf entry for host". Porzucono bazę danych na heroku dla bazy PostgreSql stojącej na Arubie. Rozwiązało to problem, SonarQube uruchamiał się.

Założono nowy projekt w Jenkinsie który pożenił go z SonarQube: https://medium.com/@amitvermaa93/jenkins-sonarqube-integration-129f5c49c4ca. Ważne było dodanie odpowiednich deklaracji w pliku /opt/sonarqube/conf/sonar-jenkins.properties: https://docs.sonarqube.org/latest/analysis/analysis-parameters/. SonarQube na ten moment uruchamia po zbudowaniu projektu na gałęziach master oraz develope się i generuje raporty.
