### ISSUE TITLE
Stworzenie nowej bazy dla SonarQube

### ISSUE THREAD

**Issue by WRup** [kamroj/robot#92]
Należy stworzyć nową bazę na heroku i przypisać ją do naszej aplikacji bookrobotja7, ponieważ SonarQube tworzy na swoje potrzeby sporo tabel i trzyma tam dane potrzebne do poprawnego działania. Aby nie zaśmiecać bazy produkcyjnej należy stowrzyć nową stricte dla SonarQube
- [x] Stworzenie bazy na heorku
- [x] Dodanie bazy do istniejącego projektu

**Comment by marcinogo** [comment]
Kolejna baza danych na Heroku. Sonar tworzy w niej wymagane tabele / rekordy.
